ogg:
	g++ -c full.C sort.C fact.C wave.C wdevstd.C analisigoccia.C average.C stdDev.C sums.C error.C
comp: ogg
	g++ full.o sort.o fact.o wave.o wdevstd.o analisigoccia.o average.o stdDev.o sums.o error.o -o full.x
ese: comp
	./full.x